# general content

title: worldx3 | Alex M. Gorgal
email: alex@worldx3.com
description: > # this means to ignore newlines until "baseurl:"
  Me llamo Alex M. Gorgal y soy diseñador de productos y servicios digitales para varias empresas y organizaciones.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://worldx3.com" # the base hostname & protocol for your site, e.g. http://example.com
username_github: gruncho
username_twitter: gruncho
username_dribbble: gruncho

# Build settings

markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Sass settings

sass:
  sass_dir: _scss
  style: :compressed

# Gems

gems:
  - jekyll-feed